========
Examples
========

--------------
hello_world.py
--------------

.. literalinclude:: ../examples/hello_world.py
   :pyobject: main
			       
----------------
hello_timer_1.py
----------------

.. literalinclude:: ../examples/hello_timer_1.py
   :pyobject: main
		    
----------------
hello_timer_2.py
----------------

.. literalinclude:: ../examples/hello_timer_2.py
   :pyobject: main
		    
-----------------
hello_filter_1.py
-----------------

.. literalinclude:: ../examples/hello_filter_1.py
   :pyobject: main

-----------------
hello_filter_2.py
-----------------

.. literalinclude:: ../examples/hello_filter_2.py
   :pyobject: main

--------------------
simulated_motor_1.py
--------------------

.. literalinclude:: ../examples/simulated_motor_1.py
   :pyobject: main

--------------------
simulated_motor_2.py
--------------------

.. literalinclude:: ../examples/simulated_motor_2.py
   :pyobject: main

-----------
rc_motor.py
-----------

.. literalinclude:: ../examples/simulated_motor_2.py
   :pyobject: main

-------------------
rc_motor_control.py
-------------------

.. literalinclude:: ../examples/rc_motor_control.py
   :pyobject: main

-------------------
rc_mip_balance.py
-------------------

.. literalinclude:: ../examples/rc_mip_balance.py
   :pyobject: main
	      
