Module `pyctrl.system`
======================
      
.. automodule:: pyctrl.system
   :members:
   :show-inheritance:
   :inherited-members:

Module `pyctrl.system.tf`
=========================

.. automodule:: pyctrl.system.tf
   :members:
   :show-inheritance:

Module `pyctrl.system.ss`
=========================

.. automodule:: pyctrl.system.ss
   :members:
   :show-inheritance:
   :inherited-members:
      
Module `pyctrl.system.ode`
==========================
      
.. automodule:: pyctrl.system.ode
   :members:
   :show-inheritance:
   :inherited-members:
